### ISSUE TITLE
Does NATS streaming client manage reconnect properly?

### ISSUE THREAD

**Issue by zshamrock** [nats-io/java-nats-streaming#40]
NATS connection provides various callback methods, like `setDisconnectedCallback`, `setClosedCallback` and others. As well as exposes the connection stats over `isClosed`, `isConnected`, `isReconnecting`.

NATS streaming connection on the opposite doesn't have any of those methods above. Although it is possible to get the underlying NATS connection using `getNatsConnection` to check the state (is it a recommended to do anyway?), it is not possible to reset the NATS connection on the NATS streaming connection after.

Does it mean that NATS streaming connection manage itself all the re-connection logic,  or the application code should check for the underlying NATS connection status, and re-create NATS streaming connection instead if the underlying NATS connection is closed.

**Comment by zshamrock** [comment]
@mcqueary could you, please, comment on this? What is the overall status with this client development, not much activity in the recent days.

**Comment by ColinSullivan1** [comment]
@zshamrock , this client is still being supported and maintained.

It is not possible to reset the NATS connection under the NATS streaming connection at this time.  NATS streaming handles reconnections - the streaming server will redeliver any messages you may have missed while the underlying NATS client has been attempting to reconnect.

It is a different story when the underlying NATS connection is closed, though.  I suggest using the `onClose` callback of the underlying NATS connection to detect if you've unintentionally lost connection to the NATS server.  If you encounter an unintentional close (meaning NATS tried to reconnect and couldn't) then you know the NATS streaming client is in an invalid state without attempting to use a NATS streaming API.  After connectivity issues have been resolved, recreating the NATS streaming connection will prompt the NATS streaming server to deliver any messages you may have missed (based on your client options).

Does this make sense?

**Comment by zshamrock** [comment]
Thank you, @ColinSullivan1, for clarifying NATS streaming client internals. 
Will take a look into `onClose` callback.

**Comment by ccassar** [comment]
@ColinSullivan1 

> After connectivity issues have been resolved, recreating the NATS streaming connection will prompt the NATS streaming server to deliver any messages you may have missed (based on your client options).

Do subscriptions have to be replayed after the NATS streaming connection is recreated? i.e.  do we need to reissue QueueSubscribe calls post reconnect?

**Comment by ColinSullivan1** [comment]
@ccassar Not necessarily.  You are correct in that subscriptions information is retained with the server - so long as the subscription remains active (has not been closed), regardless of store type, in the case of interruption of service the server will detect that messages it has sent have not been acknowledged, and will resend them.

If you are using memory mode, so long as the streaming server remained running, keeping subscription and message state in memory, it will behave the same as a server with a file based store.

**Comment by ccassar** [comment]
Thanks @ColinSullivan1 . The case I was experimenting with is the one where we lose the NATS streaming server. In that case, and while using memory mode, and where the underlying NATS server connections are unaffected, it is not clear there is any signal a client can trigger off in order to resubscribe.

**Comment by kozlovic** [comment]
@ccassar When using a Streaming server with memory store, after the server is restarted, all existing clients will start getting timeout errors on all their requests: publishing messages, creating subscriptions, closing things, etc... because the Server with memory store uses unique generated internal subjects to communicate with its clients.
You are correct that if you lose only the server, you may not have a signal on the client (except for all the timeouts) to realize that the connections (and not only subscriptions) should be recreated.
