### ISSUE TITLE
Integration with Spring

### ISSUE THREAD

**Issue by sachinwalia2k8** [nats-io/java-nats-streaming#52]
Spring  supports the notion of MessageListener with AMQP/Kafka/JMS where you can define the concurrent instances that will be created by container as a recipient of messages from Queue. 

I am trying to understand how similar thing is possible with Nats Streaming Java API.

What I could gather from documentation is as below (Please correct if I am mistaken here):
- Inject ConnectionFactory (seems a candidate for being a Singleton)
- Create an Instance of Connection as subscriptions are tied to Connection as evident from following code block:
```
ConnectionFactory cf = new ConnectionFactory(clusterID, clientID);
Connection sc = cf.createConnection();
Subscription sub = sc.subscribe("foo", new MessageHandler() {
  public void onMessage(Message m) {
    latch.countDown();
    System.out.printf("Received a message: %s\n", new String(m.getData()));
  }
}, new SubscriptionOptions.Builder().deliverAllAvailable().build());
```
- It seems possible that we define MessageHandler as a Bean with prototype scope so that instances are created on-demand

Questions:

- How do we create certain number of listener instances (message handler) during container bootstrap?
- Is subscription always tied with one single connection? 
- Is there a notion of connection pooling of some sort?

thanks.

**Comment by ColinSullivan1** [comment]
@sachinwalia2k8 , Thank you for using NATS!  To answer your questions:

> How do we create certain number of listener instances (message handler) during container bootstrap?

One approach might be to have more than one subscription.  You can create multiple subscriptions on the same subject, and your application can restrict the number of subscriptions.  Since message listeners and subscriptions have a 1:1 relationship, this may be a cleaner way for you to control message listener instances.

> Is a subscription always tied with one single connection?

Yes, a subscription is tied to the connection it was created on.

> Is there a notion of connection pooling of some sort?

No, there isn't at this time.  Each connection requires a unique client ID (to maintain client state at the server), so pooling could result in unpredictable behavior.

Did this answer your questions?

Regards,
Colin

**Comment by sachinwalia2k8** [comment]
Thanks @ColinSullivan1 for your response. So if we follow this strategy then one way to achieve this would be to spawn threads from within listener itself. Since creating on-demand thread in java is expensive so I guess bootstrapping a thread pool during startup could be one strategy to reduce the latency. So at this time it sounds like listener could be envisaged as a control plane for launching further consumers. Let me know if this sounds about right or if there is a scalability/consistency issue? 

thanks.

**Comment by ColinSullivan1** [comment]
@sachinwalia2k8 , absolutely, happy to help.  What you described sounds good; I don't see any concurrency issues.  

One thing to consider is manually acknowledging messages since you are handing them off to another thread.  An example of using `setManualAcks(true)` to do this can be found [here](https://github.com/nats-io/java-nats-streaming#message-acknowledgements-and-redelivery).

Please let us know how this turns out for you!

Thanks,
Colin

**Comment by sachinwalia2k8** [comment]
Thanks @ColinSullivan1 I am going to try this approach today. My project has mix of both Go and Java based services that needs to intercommunicate. From Go it is fairly straightforward but I wasn't sure the right approach on the Java side.

**Comment by ColinSullivan1** [comment]
Closing as part of housekeeping.  If this is still an issue, please reopen this.
