### ISSUE TITLE
Driver doesn't recover after NATs goes away

### ISSUE THREAD

**Issue by jebbench** [nats-io/java-nats-streaming#67]
If NATs is unreachable for any reason the driver does not recover.

Using `0.5.0-SNAPSHOT`.

```
java.io.IOException: stan: publish ack timeout
    at io.nats.streaming.StreamingConnectionImpl.publish(StreamingConnectionImpl.java:306)
```

```
java.lang.IllegalStateException: nats: connection closed
	at io.nats.client.ConnectionImpl.publish(ConnectionImpl.java:1957)
	at io.nats.client.ConnectionImpl.publish(ConnectionImpl.java:2041)
	at io.nats.streaming.StreamingConnectionImpl.publish(StreamingConnectionImpl.java:373)
	at io.nats.streaming.StreamingConnectionImpl.publish(StreamingConnectionImpl.java:301) 
```

To replicate:

Create an application that emits messages to NATs and run it.
Allow it connect to NATs and start emitting messages.
Kill NATS.
The application will emit `java.lang.IllegalStateException: nats: connection closed`.
Restart NATS.
The application will continue to emit `java.lang.IllegalStateException: nats: connection closed`.

Expected behaviour:
After NATs is restarted the application should successfully emit messages.

**Comment by ColinSullivan1** [comment]
@jebbench , this is because the wrapped NATS connection underneath the java-nats-streaming API has been closed.  At this point, the best approach is to clear up your streaming connection and recreate it to pick up where you left off.  It's best to think of NATS streaming as a layer above NATS, where it creates a basic NATS connection for you.  This behavior can be overridden.

To override connection defaults, you can create a more resilient NATS connection by using java-nats, and set the [maxReconnect()](https://github.com/nats-io/java-nats/blob/master/src/main/java/io/nats/client/Options.java#L574) parameter to something very large. Then you can pass this connection to NATS streaming connection via [StreamingConnectionFactory.setNatsConnection(...)](https://github.com/nats-io/java-nats-streaming/blob/master/src/main/java/io/nats/streaming/StreamingConnectionFactory.java#L189).

You can also tweak other parameters on the NATS connection such as max pings out, and ping interval.

Does this make sense?

Thanks,
Colin

**Comment by jebbench** [comment]
We've worked around this by wrapping the NATs streaming connection in our own wrapper that will reconnect, retry publish calls and recreate subscriptions if the disconnect callback gets called - this seems to be working (but it would be nice of the driver itself was able to do so for us).

**Comment by ColinSullivan1** [comment]
The underlying NATS connection, if configured to do so, can attempt to continually reconnect saving you from having to recreate subscriptions.  However, it won't retry outstanding published messages - a nice addition in your wrapper.

**Comment by zshamrock** [comment]
So how this relates to #84? Because what I see using the default underlying NATS connection reconnection works fine for me (although I am using `0.4.0` version). Only thing I don't see is that there is no republishing. Not sure whether it should be, as there is one in the NATS client itself.

Another question, @ColinSullivan1 you've mentioned
> ...recreate it to pick up where you left off.

How to do that?

**Comment by zshamrock** [comment]
Also @jebbench how you do the republishing in your wrapper, i.e. you keep the buffer of the unsent messages, and retry them when the connection is re-established?

**Comment by sasbury** [comment]
We are treating streaming as a layer on top of nats, so there is no auto-reconnect in any of the libraries at the streaming level. I am looking at adding support for a disconnect callback, but the current library standard is to leave it up to the app to reconnect explicitely at the streaming level.
