### ISSUE TITLE
jnats interoperability / request-reply

### ISSUE THREAD

**Issue by jnsone11** [nats-io/java-nats-streaming#9]
It seems jnats and java nats streaming are currently not interoperable (pub sub on the same subjects does not work for me)?

Creating temp subjects via streaming is a way to achieve request-reply.
However, it seems the client denies to open too many subjects.

I feel a bit uncomfortable having a jnats client besides a streaming client in the same application.
Any suggestions?

Cheers
Jens

**Comment by kozlovic** [comment]
You are right that NATS Streaming and NATS are not interoperable. If your application needs streaming and basic NATS, then you would need 2 different connections. Yet, they will not be able to communicate with each other as you have discovered.

If you do request-reply, you don't need persistence. The reason is that with req/reply you get an even higher quality of service: you have an end-to-end confirmation that the receiver has processed the message. You achieve at-least-once delivery with request/reply, and don't need persistence for that.

NATS Streaming was introduced for use cases where one wants at-least-once but without doing request-reply, more of a queueing semantic: publish even if subscriber is not running, messages can be consumed at a later time.

Let me know if this clears things up.

**Comment by jnsone11** [comment]
Thank you for your post.

I was asking because of use cases where you do request reply but also want to log that particular activity at least once via a second subscription.

Maybe a client side Proxy from default to Stream might help.

**Comment by mcqueary** [comment]
@jnsone11 Jens, you could certainly subscribe to `>` on the NATS side, and see all the NATS Streaming messages. The other option would be to have your NATS Streaming requestor clients use well-known reply subjects (vs auto-generated INBOX subjects) that can be subscribed to by your 'logger' NATS client. If the logger NATS client knows the request and reply subjects in advance, you can log all the requests/replies without issue.

Ultimately
